version: 0.1

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -e .
  pre_build:
    commands:
      - find . -name "*.py" -exec pylint '{}' \;
      - cd bktlst && python tests/test_index.py -v
artifacts:
  files:
    - '**/*'
  discard-paths: no